services:
  data:
    image: 'postgres:15-alpine'
    container_name: 'data'
    restart: 'always'
    volumes:
      - 'data:/var/lib/'
    environment:
      - 'POSTGRES_DB=escuela'
      -  'POSTGRES_USER=escuela'
      - 'POSTGRES_PASSWORD=12345678'

    ports:
      - '6060:5432'

volumes:
  'data':